import '../../features/bible/domain/models/bible_book.dart';

abstract class BibleBookList {
  static const List<BibleBook> all = [
    BibleBook(id: 'GEN', name: 'Genesis', chapterCount: 50),
    BibleBook(id: 'EXO', name: 'Exodus', chapterCount: 40),
    BibleBook(id: 'LEV', name: 'Leviticus', chapterCount: 27),
    BibleBook(id: 'NUM', name: 'Numbers', chapterCount: 36),
    BibleBook(id: 'DEU', name: 'Deuteronomy', chapterCount: 34),
    BibleBook(id: 'JOS', name: 'Joshua', chapterCount: 24),
    BibleBook(id: 'JDG', name: 'Judges', chapterCount: 21),
    BibleBook(id: 'RUT', name: 'Ruth', chapterCount: 4),
    BibleBook(id: '1SA', name: '1 Samuel', chapterCount: 31),
    BibleBook(id: '2SA', name: '2 Samuel', chapterCount: 24),
    BibleBook(id: '1KI', name: '1 Kings', chapterCount: 22),
    BibleBook(id: '2KI', name: '2 Kings', chapterCount: 25),
    BibleBook(id: '1CH', name: '1 Chronicles', chapterCount: 29),
    BibleBook(id: '2CH', name: '2 Chronicles', chapterCount: 36),
    BibleBook(id: 'EZR', name: 'Ezra', chapterCount: 10),
    BibleBook(id: 'NEH', name: 'Nehemiah', chapterCount: 13),
    BibleBook(id: 'EST', name: 'Esther', chapterCount: 10),
    BibleBook(id: 'JOB', name: 'Job', chapterCount: 42),
    BibleBook(id: 'PSA', name: 'Psalms', chapterCount: 150),
    BibleBook(id: 'PRO', name: 'Proverbs', chapterCount: 31),
    BibleBook(id: 'ECC', name: 'Ecclesiastes', chapterCount: 12),
    BibleBook(id: 'SNG', name: 'Song of Solomon', chapterCount: 8),
    BibleBook(id: 'ISA', name: 'Isaiah', chapterCount: 66),
    BibleBook(id: 'JER', name: 'Jeremiah', chapterCount: 52),
    BibleBook(id: 'LAM', name: 'Lamentations', chapterCount: 5),
    BibleBook(id: 'EZK', name: 'Ezekiel', chapterCount: 48),
    BibleBook(id: 'DAN', name: 'Daniel', chapterCount: 12),
    BibleBook(id: 'HOS', name: 'Hosea', chapterCount: 14),
    BibleBook(id: 'JOL', name: 'Joel', chapterCount: 3),
    BibleBook(id: 'AMO', name: 'Amos', chapterCount: 9),
    BibleBook(id: 'OBA', name: 'Obadiah', chapterCount: 1),
    BibleBook(id: 'JON', name: 'Jonah', chapterCount: 4),
    BibleBook(id: 'MIC', name: 'Micah', chapterCount: 7),
    BibleBook(id: 'NAM', name: 'Nahum', chapterCount: 3),
    BibleBook(id: 'HAB', name: 'Habakkuk', chapterCount: 3),
    BibleBook(id: 'ZEP', name: 'Zephaniah', chapterCount: 3),
    BibleBook(id: 'HAG', name: 'Haggai', chapterCount: 2),
    BibleBook(id: 'ZEC', name: 'Zechariah', chapterCount: 14),
    BibleBook(id: 'MAL', name: 'Malachi', chapterCount: 4),
    BibleBook(id: 'MAT', name: 'Matthew', chapterCount: 28),
    BibleBook(id: 'MRK', name: 'Mark', chapterCount: 16),
    BibleBook(id: 'LUK', name: 'Luke', chapterCount: 24),
    BibleBook(id: 'JHN', name: 'John', chapterCount: 21),
    BibleBook(id: 'ACT', name: 'Acts', chapterCount: 28),
    BibleBook(id: 'ROM', name: 'Romans', chapterCount: 16),
    BibleBook(id: '1CO', name: '1 Corinthians', chapterCount: 16),
    BibleBook(id: '2CO', name: '2 Corinthians', chapterCount: 13),
    BibleBook(id: 'GAL', name: 'Galatians', chapterCount: 6),
    BibleBook(id: 'EPH', name: 'Ephesians', chapterCount: 6),
    BibleBook(id: 'PHP', name: 'Philippians', chapterCount: 4),
    BibleBook(id: 'COL', name: 'Colossians', chapterCount: 4),
    BibleBook(id: '1TH', name: '1 Thessalonians', chapterCount: 5),
    BibleBook(id: '2TH', name: '2 Thessalonians', chapterCount: 3),
    BibleBook(id: '1TI', name: '1 Timothy', chapterCount: 6),
    BibleBook(id: '2TI', name: '2 Timothy', chapterCount: 4),
    BibleBook(id: 'TIT', name: 'Titus', chapterCount: 3),
    BibleBook(id: 'PHM', name: 'Philemon', chapterCount: 1),
    BibleBook(id: 'HEB', name: 'Hebrews', chapterCount: 13),
    BibleBook(id: 'JAS', name: 'James', chapterCount: 5),
    BibleBook(id: '1PE', name: '1 Peter', chapterCount: 5),
    BibleBook(id: '2PE', name: '2 Peter', chapterCount: 3),
    BibleBook(id: '1JN', name: '1 John', chapterCount: 5),
    BibleBook(id: '2JN', name: '2 John', chapterCount: 1),
    BibleBook(id: '3JN', name: '3 John', chapterCount: 1),
    BibleBook(id: 'JUD', name: 'Jude', chapterCount: 1),
    BibleBook(id: 'REV', name: 'Revelation', chapterCount: 22),
  ];
}
