import '../../features/bible/domain/entities/bible_book.dart';

const kBibleBooks = <BibleBook>[
  // Old Testament
  BibleBook(id: 'GEN', name: 'Genesis', abbreviation: 'Gen', testament: Testament.old, totalChapters: 50),
  BibleBook(id: 'EXO', name: 'Exodus', abbreviation: 'Exo', testament: Testament.old, totalChapters: 40),
  BibleBook(id: 'LEV', name: 'Leviticus', abbreviation: 'Lev', testament: Testament.old, totalChapters: 27),
  BibleBook(id: 'NUM', name: 'Numbers', abbreviation: 'Num', testament: Testament.old, totalChapters: 36),
  BibleBook(id: 'DEU', name: 'Deuteronomy', abbreviation: 'Deu', testament: Testament.old, totalChapters: 34),
  BibleBook(id: 'JOS', name: 'Joshua', abbreviation: 'Jos', testament: Testament.old, totalChapters: 24),
  BibleBook(id: 'JDG', name: 'Judges', abbreviation: 'Jdg', testament: Testament.old, totalChapters: 21),
  BibleBook(id: 'RUT', name: 'Ruth', abbreviation: 'Rut', testament: Testament.old, totalChapters: 4),
  BibleBook(id: '1SA', name: '1 Samuel', abbreviation: '1Sa', testament: Testament.old, totalChapters: 31),
  BibleBook(id: '2SA', name: '2 Samuel', abbreviation: '2Sa', testament: Testament.old, totalChapters: 24),
  BibleBook(id: '1KI', name: '1 Kings', abbreviation: '1Ki', testament: Testament.old, totalChapters: 22),
  BibleBook(id: '2KI', name: '2 Kings', abbreviation: '2Ki', testament: Testament.old, totalChapters: 25),
  BibleBook(id: '1CH', name: '1 Chronicles', abbreviation: '1Ch', testament: Testament.old, totalChapters: 29),
  BibleBook(id: '2CH', name: '2 Chronicles', abbreviation: '2Ch', testament: Testament.old, totalChapters: 36),
  BibleBook(id: 'EZR', name: 'Ezra', abbreviation: 'Ezr', testament: Testament.old, totalChapters: 10),
  BibleBook(id: 'NEH', name: 'Nehemiah', abbreviation: 'Neh', testament: Testament.old, totalChapters: 13),
  BibleBook(id: 'EST', name: 'Esther', abbreviation: 'Est', testament: Testament.old, totalChapters: 10),
  BibleBook(id: 'JOB', name: 'Job', abbreviation: 'Job', testament: Testament.old, totalChapters: 42),
  BibleBook(id: 'PSA', name: 'Psalms', abbreviation: 'Psa', testament: Testament.old, totalChapters: 150),
  BibleBook(id: 'PRO', name: 'Proverbs', abbreviation: 'Pro', testament: Testament.old, totalChapters: 31),
  BibleBook(id: 'ECC', name: 'Ecclesiastes', abbreviation: 'Ecc', testament: Testament.old, totalChapters: 12),
  BibleBook(id: 'SNG', name: 'Song of Solomon', abbreviation: 'Sng', testament: Testament.old, totalChapters: 8),
  BibleBook(id: 'ISA', name: 'Isaiah', abbreviation: 'Isa', testament: Testament.old, totalChapters: 66),
  BibleBook(id: 'JER', name: 'Jeremiah', abbreviation: 'Jer', testament: Testament.old, totalChapters: 52),
  BibleBook(id: 'LAM', name: 'Lamentations', abbreviation: 'Lam', testament: Testament.old, totalChapters: 5),
  BibleBook(id: 'EZK', name: 'Ezekiel', abbreviation: 'Ezk', testament: Testament.old, totalChapters: 48),
  BibleBook(id: 'DAN', name: 'Daniel', abbreviation: 'Dan', testament: Testament.old, totalChapters: 12),
  BibleBook(id: 'HOS', name: 'Hosea', abbreviation: 'Hos', testament: Testament.old, totalChapters: 14),
  BibleBook(id: 'JOL', name: 'Joel', abbreviation: 'Jol', testament: Testament.old, totalChapters: 3),
  BibleBook(id: 'AMO', name: 'Amos', abbreviation: 'Amo', testament: Testament.old, totalChapters: 9),
  BibleBook(id: 'OBA', name: 'Obadiah', abbreviation: 'Oba', testament: Testament.old, totalChapters: 1),
  BibleBook(id: 'JON', name: 'Jonah', abbreviation: 'Jon', testament: Testament.old, totalChapters: 4),
  BibleBook(id: 'MIC', name: 'Micah', abbreviation: 'Mic', testament: Testament.old, totalChapters: 7),
  BibleBook(id: 'NAM', name: 'Nahum', abbreviation: 'Nam', testament: Testament.old, totalChapters: 3),
  BibleBook(id: 'HAB', name: 'Habakkuk', abbreviation: 'Hab', testament: Testament.old, totalChapters: 3),
  BibleBook(id: 'ZEP', name: 'Zephaniah', abbreviation: 'Zep', testament: Testament.old, totalChapters: 3),
  BibleBook(id: 'HAG', name: 'Haggai', abbreviation: 'Hag', testament: Testament.old, totalChapters: 2),
  BibleBook(id: 'ZEC', name: 'Zechariah', abbreviation: 'Zec', testament: Testament.old, totalChapters: 14),
  BibleBook(id: 'MAL', name: 'Malachi', abbreviation: 'Mal', testament: Testament.old, totalChapters: 4),
  // New Testament
  BibleBook(id: 'MAT', name: 'Matthew', abbreviation: 'Mat', testament: Testament.newTestament, totalChapters: 28),
  BibleBook(id: 'MRK', name: 'Mark', abbreviation: 'Mrk', testament: Testament.newTestament, totalChapters: 16),
  BibleBook(id: 'LUK', name: 'Luke', abbreviation: 'Luk', testament: Testament.newTestament, totalChapters: 24),
  BibleBook(id: 'JHN', name: 'John', abbreviation: 'Jhn', testament: Testament.newTestament, totalChapters: 21),
  BibleBook(id: 'ACT', name: 'Acts', abbreviation: 'Act', testament: Testament.newTestament, totalChapters: 28),
  BibleBook(id: 'ROM', name: 'Romans', abbreviation: 'Rom', testament: Testament.newTestament, totalChapters: 16),
  BibleBook(id: '1CO', name: '1 Corinthians', abbreviation: '1Co', testament: Testament.newTestament, totalChapters: 16),
  BibleBook(id: '2CO', name: '2 Corinthians', abbreviation: '2Co', testament: Testament.newTestament, totalChapters: 13),
  BibleBook(id: 'GAL', name: 'Galatians', abbreviation: 'Gal', testament: Testament.newTestament, totalChapters: 6),
  BibleBook(id: 'EPH', name: 'Ephesians', abbreviation: 'Eph', testament: Testament.newTestament, totalChapters: 6),
  BibleBook(id: 'PHP', name: 'Philippians', abbreviation: 'Php', testament: Testament.newTestament, totalChapters: 4),
  BibleBook(id: 'COL', name: 'Colossians', abbreviation: 'Col', testament: Testament.newTestament, totalChapters: 4),
  BibleBook(id: '1TH', name: '1 Thessalonians', abbreviation: '1Th', testament: Testament.newTestament, totalChapters: 5),
  BibleBook(id: '2TH', name: '2 Thessalonians', abbreviation: '2Th', testament: Testament.newTestament, totalChapters: 3),
  BibleBook(id: '1TI', name: '1 Timothy', abbreviation: '1Ti', testament: Testament.newTestament, totalChapters: 6),
  BibleBook(id: '2TI', name: '2 Timothy', abbreviation: '2Ti', testament: Testament.newTestament, totalChapters: 4),
  BibleBook(id: 'TIT', name: 'Titus', abbreviation: 'Tit', testament: Testament.newTestament, totalChapters: 3),
  BibleBook(id: 'PHM', name: 'Philemon', abbreviation: 'Phm', testament: Testament.newTestament, totalChapters: 1),
  BibleBook(id: 'HEB', name: 'Hebrews', abbreviation: 'Heb', testament: Testament.newTestament, totalChapters: 13),
  BibleBook(id: 'JAS', name: 'James', abbreviation: 'Jas', testament: Testament.newTestament, totalChapters: 5),
  BibleBook(id: '1PE', name: '1 Peter', abbreviation: '1Pe', testament: Testament.newTestament, totalChapters: 5),
  BibleBook(id: '2PE', name: '2 Peter', abbreviation: '2Pe', testament: Testament.newTestament, totalChapters: 3),
  BibleBook(id: '1JN', name: '1 John', abbreviation: '1Jn', testament: Testament.newTestament, totalChapters: 5),
  BibleBook(id: '2JN', name: '2 John', abbreviation: '2Jn', testament: Testament.newTestament, totalChapters: 1),
  BibleBook(id: '3JN', name: '3 John', abbreviation: '3Jn', testament: Testament.newTestament, totalChapters: 1),
  BibleBook(id: 'JUD', name: 'Jude', abbreviation: 'Jud', testament: Testament.newTestament, totalChapters: 1),
  BibleBook(id: 'REV', name: 'Revelation', abbreviation: 'Rev', testament: Testament.newTestament, totalChapters: 22),
];
